backchat/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
import accounts.views as user_views

app_name = 'auth'
urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout')
]

backchat/backchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('', include('chat.urls')),
]

backchat/chat/urls.py
from django.urls import path
from django.views.generic import TemplateView

from chat import views

app_name = 'chat'
urlpatterns = [
    path("", TemplateView.as_view(template_name='base.html'), name='index'),
    path("chat/room/<str:slug>/", views.index, name='chat'),
    path("create/", views.room_create, name='room-create'),
    path("join/", views.room_join, name='room-join'),
]

backchat/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    pass

backchat/chat/models.py
from django.db import models
from accounts.models import User


# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(unique=True)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            self.room.name+' - ' + str(self.user.username) + ' : ' + str(self.message)
        )

backchat/accounts/forms.py
from .models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

backchat/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from .forms import UserRegisterForm


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, "Your account has been created! You are now able to log in.")
            return redirect("chat:index")
    else:
        form = UserRegisterForm()

    context = {
        'form': form
    }
    return render(request, 'accounts/register.html', context)

backchat/chat/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify

from chat.models import Room

import string
import random


# Create your views here.
@login_required
def index(request, slug):
    room = Room.objects.get(slug=slug)
    context = {
        'name': room.name,
        'slug': room.slug
    }
    return render(request, 'chat/room.html', context)


@login_required
def room_create(request):
    if request.method == "POST":
        room_name = request.POST['room_name']
        uid = str(''.join(random.choices(string.ascii_letters + string.digits, k=4)))
        room_slug = slugify(room_name + "_" + uid)
        room = Room.objects.create(name=room_name, slug=room_slug)
        context = {
            'slug': room.slug
        }
        return redirect(reverse('chat:chat', kwargs=context))
    else:
        return render(request, 'chat/create.html')


@login_required
def room_join(request):
    if request.method == "POST":
        room_slug = request.POST['room_slug']
        room = Room.objects.get(slug=room_slug)
        context = {
            'slug': room.slug
        }
        return redirect(reverse('chat:chat', kwargs=context))
    else:
        return render(request, 'chat/join.html')

backchat/chat/templates/chat/room.html
{% extends 'base.html' %}

{% block base %}
    <h2>{{ name }}</h2>
    <div hx-ws="send:/chat/{{ slug }}/">
        <form hx-ws="send:submit">
            <label for="message">Message</label>
            <input type="text" id="message" name="message">
            <input type="submit">
        </form>
    </div>
    <div id="messages"></div>
{% endblock %}

backchat/templates/accounts/login.html
{% extends 'base.html' %}

{% block base %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h5 class="card-title text-center">LOG IN</h5>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Password</label>
                            {{ form.password }}
                        </div>
                        <div class="text-center">
                            <button class="btn btn-primary" type="submit">Log In</button>
                        </div>
                    </form>
                    <div class="text-center mt-3">
                        <small class="text-muted">
                            Don't have an account? <a href="{% url 'auth:register' %}">Sign up</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backchat/templates/accounts/logout.html
{% extends 'base.html' %}

{% block base %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h2 class="card-title text-center">You have been logged out</h2>
                    <div class="border-top pt-3 text-center">
                        <a href="{% url 'auth:login' %}">Log In Again</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backchat/templates/accounts/register.html
{% extends 'base.html' %}

{% block base %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Register Now</h5>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="id_password1" class="form-label">Password</label>
                            {{ form.password1 }}
                        </div>
                        <div class="mb-3">
                            <label for="id_password2" class="form-label">Confirm Password</label>
                            {{ form.password2 }}
                        </div>
                        <div class="text-center">
                            <button class="btn btn-primary" type="submit">Sign Up</button>
                        </div>
                    </form>
                    <div class="text-center mt-3">
                        <small class="text-muted">
                            Already Have An Account? <a href="{% url 'auth:login' %}">Log In</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backchat/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://unpkg.com/htmx.org@1.9.2"></script>
    <title>Chat App</title>
</head>
<body hx-ext="ws" class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'chat:index' %}">Home</a>
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'auth:logout' %}">Logout</a>
            {% else %}
                <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
            {% endif %}
        </div>
    </nav>

    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <br>
        <h1 class="mt-5">Back Chat</h1>
        {% block base %}
        <div class="my-3">
            <a class="btn btn-primary" href="{% url 'chat:room-join' %}">Join Room</a>
            <a class="btn btn-secondary" href="{% url 'chat:room-create' %}">Create Room</a>
        </div>
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

backchat/templates/chat/create.html
{% extends 'base.html' %}

{% block base %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <form method="post" action="{% url 'chat:room-create' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="room_name" class="form-label">Name:</label>
                            <input type="text" name="room_name" id="room_name" class="form-control" placeholder="Room Name">
                        </div>
                        <button type="submit" class="btn btn-primary">Create Room</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backchat/templates/chat/join.html
{% extends 'base.html' %}

{% block base %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <form action="{% url 'chat:room-join' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="room_name" class="form-label">Code:</label>
                            <input type="text" name="room_name" id="room_name" class="form-control" placeholder="Room Code" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Join Room</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

backchat/templates/chat/room.html
{% extends 'base.html' %}

{% block base %}
<div class="container">
    <h2>{{ name }}</h2>
    <p>Room Code: {{ slug }}</p>
    <div class="row">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <div hx-ws="connect:/chat/{{ slug }}/">
                        <form hx-ws="send:submit">
                            <div class="form-group">
                                <label for="message">Message:</label>
                                <input id="message" name="message" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary">Send</button>
                        </form>
                    </div>
                    <div id="messages" class="mt-3"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}